### What is the Keras? 

- Keras is the hight level API of the tensorflow platform.  It provides an approachable, hight-productive interface for solving machine learning problems, with a focus on modern deep learning.

- It was developed with a focus on enabling fast experimentation

In [4]:
import tensorflow as tf
import keras

from keras import layers

In [15]:
model = keras.Sequential([
    layers.Dense(2,activation="relu", name = "layer1"),
    layers.Dense(6,activation="relu", name = "layer2"),
    layers.Dense(4, name ="layers3" )
])

In [16]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [17]:
y = model(x)
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [18]:
len(model.layers)

3

In [19]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                  │ (3, 2)                 │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer2 (Dense)                  │ (3, 6)                 │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layers3 (Dense)                 │ (3, 4)                 │            28 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

: 